Differential Chassis fabrication
marsiitr/Differential-Chasis pull request #1
Opened 2018-06-19 11:12 UTC by rg0699

@Shubhanshu07

2018-06-19 15:40 UTC, Shubhanshu07 commented
*@rg0699* 
### Following changes are needed
1. Make readme.md in place of doc file.
2. Use markdown syntax in readme file.
3. Also add images and videos in a separate folder.

2018-06-20 05:53 UTC, palnabarun commented
@Shubhanshu07  Try to put inline reviews like I did just now.

2018-06-20 05:56 UTC, palnabarun commented on README.md
> +# CHASSIS
Add blank new line between each block.

2018-06-20 05:56 UTC, palnabarun commented on README.md
> +[differential](https://ai2-s2-public.s3.amazonaws.com/figures/2017-08-08/176dd7b3289267d8c693fb16f0d6fea480b5fad5/2-Figure2-1.png)
This would be a hyperlink. For rendering images, use `! [ ] ( )`

2018-06-20 05:56 UTC, palnabarun commented on README.md
> +[differential](https://ai2-s2-public.s3.amazonaws.com/figures/2017-08-08/176dd7b3289267d8c693fb16f0d6fea480b5fad5/2-Figure2-1.png)
Do the same for each image in the Readme

2018-06-20 05:56 UTC, palnabarun commented on README.md
> +1)Caster wheel
Use Ordered list like this:
```
1. One
2. Two
```

2018-06-20 05:56 UTC, palnabarun commented on README.md
> +-Mounting of 3D printed gears on both sides of bot.
Add a space between `-` and the content for an unordered list.

2018-06-20 05:56 UTC, palnabarun commented on README.md
> +## WORK LEFT:
Please do not put colons at the end of a header

2018-06-20 06:00 UTC, palnabarun reviewed
@rg0699  Please implement the reviews.

2018-06-20 06:22 UTC, Shubhanshu07 commented on README.md
> +# TEAM MEMBERS:
@rg0699  Write team members and mentors name separately and in alphabetical order with their Github link

2018-06-20 06:25 UTC, agshubhs requested changes
Add in actual images of the bot in the readme file as well as in a separate folder

2018-06-20 10:04 UTC, agshubhs approved these changes

2018-06-20 10:17 UTC, palnabarun reviewed
@rg0699 Please edit this.

2018-06-20 10:17 UTC, palnabarun commented on README.md
> +1.Caster wheel
Please put a space between the number and the text.

2018-06-20 10:17 UTC, palnabarun commented
The PR Looks Good to me. Please make the above suggested change and you are good to go.

2018-06-20 14:29 UTC, Shubhanshu07 commented on README.md
> +# DIFFERENTIAL CHASSIS
short the content of this paragraph and try to write these paragraph in points or bullets .

2018-06-20 15:03 UTC, palnabarun commented
Looks Good To Me.

Squashing and Mergin.

2018-06-20 15:04 UTC, merged

2018-06-20 15:05 UTC, palnabarun commented
Good work. @rg0699 

@Shubhanshu07  Thank you for moderating the PR.

2018-06-20 15:20 UTC, rg0699 commented
thanks @palnabarun and @Shubhanshu07 sir for your guide.

2018-06-21 05:25 UTC, agshubhs commented
nice work @rg0699